export const SET_INVOICE_DETAILS = "SET_INVOICE_DETAILS";
export const SET_RECIPANT_DETAILS = "SET_RECIPANT_DETAILS";
export const SET_ISSUER_DETAILS = "SET_ISSUER_DETAILS";
export const SET_INVOICE_TABLE = "SET_INVOICE_TABLE";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
